name: CI

on: [pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    env:
      COMPOSER_VERSION: 2

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: stagerightlabs
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: stagerightlabs_test
        ports:
        - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: 8.1
            extensions: dom, curl, libxml, mbstring, bcmath, soap,
            coverage: none

      - name: Setup problem matchers
        run: |
            echo "::add-matcher::${{ runner.tool_cache }}/php.json"
            echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Composer dependency cache
        uses: actions/cache@v2
        with:
          path: ./vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install Composer Dependencies
        run: composer install --no-scripts --no-ansi --no-progress

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'npm'

      - name: Install NPM Dependencies
        run: npm install --no-progress

      - name: Run NPM Asset Pipeline
        run: npm run build

      - name: Prepare Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run PHP Test suite
        run: ./vendor/bin/phpunit
