name: tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy CI Environment File
        run: cp .env.ci .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: yarn build

      - name: Tests
        run: ./vendor/bin/phpunit --exclude-group skip
